owner: andreruffert # GitHub username
repo: up # GitHub repository name

sites: # List of endpoints to track
  - name: andreruffert.com
    url: https://andreruffert.com
  - name: letr.app
    url: https://letr.andreruffert.com
  - name: piphero.app
    url: https://piphero.app
    
status-website:
  baseUrl: /up
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime monitor

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
